name: brook
version: master
version-script: git -C parts/brook/build rev-parse --short HEAD
summary: Cross platform proxy software.
description: |
  Brook is a cross-platform(Linux/MacOS/Windows/Android/iOS) proxy software 

grade: stable
confinement: strict

parts:
  go:
    source-tag: go1.9.4
  brook:
    after: [go]
    source: .
    plugin: go
    go-importpath: github.com/txthinking/brook.git

apps:
  brook:
    command: brook
    plugs:
      - network
      - network-bind
